import {
  Organisation,
  AircraftFleet,
  TrainingBatch,
  CadetStudent,
  InstructorProfile,
  InstructorQualification,
  SimulatorResource,
  CourseSyllabusItem,
  TrainingCourse,
  StageEvaluationRecord,
  CadetAttendanceRecord,
  TrainingScheduleSession,
  FDTLDutyRecord,
} from '@/types';

export const ATO_ORGANISATION: Organisation = {
  id: 'org-gata-01',
  legal_name: 'Global Aviation Training Academy (GATA) Ltd.',
  trading_name: 'GATA Airline Training Center',
  ato_approval_number: 'DGCA/ATO/IND/2026/042',
  is_active: true,
};

export const ATO_FLEETS: AircraftFleet[] = [
  {
    id: 'fleet-a320',
    manufacturer: 'Airbus',
    model_name: 'A320',
    variant: 'CEO & NEO',
    type_rating_code: 'A320',
    category: 'JET',
    description: 'Airbus A320 family (CFM56, IAE V2500, LEAP-1A, PW1100G)',
  },
  {
    id: 'fleet-b737',
    manufacturer: 'Boeing',
    model_name: 'B737',
    variant: 'NG & MAX',
    type_rating_code: 'B737',
    category: 'JET',
    description: 'Boeing 737 Next Generation (-800/-900) & MAX 8/9 (LEAP-1B)',
  },
  {
    id: 'fleet-atr72',
    manufacturer: 'ATR',
    model_name: 'ATR 72',
    variant: '-600',
    type_rating_code: 'ATR-72-600',
    category: 'TURBOPROP',
    description: 'ATR 72-600 Glass Cockpit Regional Turboprop (PW127M)',
  },
  {
    id: 'fleet-q400',
    manufacturer: 'De Havilland',
    model_name: 'DHC-8 Q400',
    variant: 'Dash 8',
    type_rating_code: 'DHC-8-400',
    category: 'TURBOPROP',
    description: 'High-Speed Regional Turboprop (PW150A)',
  },
];

export const ATO_COURSES: TrainingCourse[] = [
  {
    id: 'crs-a320-initial',
    course_code: 'TR-A320-INITIAL',
    course_title: 'Airbus A320 Initial Type Rating (Fresher with MCC / JIT)',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    target_audience: 'FRESHER_AB_INITIO',
    has_mcc_jit: true,
    mcc_jit_hours: 20.0,
    total_ground_hours: 72.0,
    total_ftd_hours: 16.0,
    total_ffs_hours: 36.0,
    total_course_hours: 144.0,
    estimated_duration_days: 70,
    description: 'Comprehensive DGCA CAR Section 7 Approved Initial Type Rating Syllabus for CPL holders, featuring full Ground Tech, Performance, Multi-Crew Cooperation & Jet Induction (MCC/JIT), FTD flows, Level D FFS, and CA-40 Skill Test.',
    is_active: true,
    stages: [
      {
        stage_id: 'stg-a320-1',
        stage_number: 1,
        stage_name: 'Phase 1A & 1B: Technical Systems & Performance W&B',
        stage_type: 'GROUND_THEORY',
        ground_hours: 72.0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 0,
        has_exam_or_check: true,
        passing_score_percent: 80,
        requires_stage_cleared_to_proceed: true,
        description: 'Covers all A320 aircraft systems, FCOM, FCTM, MEL, weight & balance, and flight planning. Written 100-question theory exam must be cleared before entering MCC/JIT or Simulators.',
      },
      {
        stage_id: 'stg-a320-2',
        stage_number: 2,
        stage_name: 'Phase 1C: Multi-Crew Cooperation & Jet Induction Training (MCC/JIT)',
        stage_type: 'MCC_JIT',
        ground_hours: 0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 20.0,
        has_exam_or_check: true,
        passing_score_percent: 85,
        requires_stage_cleared_to_proceed: true,
        description: 'Specialized airline jet transition training focusing on PF/PM standard callouts, swept-wing high-altitude aerodynamics, jet upset dynamics, and CRM communications.',
      },
      {
        stage_id: 'stg-a320-3',
        stage_number: 3,
        stage_name: 'Phase 2A: FTD Level 2 Cockpit Flows & FMS Procedures',
        stage_type: 'FTD_PROCEDURES',
        ground_hours: 0,
        sim_ftd_hours: 16.0,
        sim_ffs_hours: 0,
        has_exam_or_check: true,
        passing_score_percent: 85,
        requires_stage_cleared_to_proceed: true,
        description: 'Fixed-base procedure trainer sessions mastering MCDU flight management, autoflight guidance, standard departure flows, and emergency memory drills.',
      },
      {
        stage_id: 'stg-a320-4',
        stage_number: 4,
        stage_name: 'Phase 2B: Full Flight Simulator Level D Manoeuvres (FFS-01 to 08)',
        stage_type: 'FFS_FULL_SIM',
        ground_hours: 0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 32.0,
        has_exam_or_check: true,
        passing_score_percent: 85,
        requires_stage_cleared_to_proceed: true,
        description: 'Full-motion simulator sessions: engine failure at V1, CAT II/III ILS precision approaches, TCAS RA, GPWS escape, windshear, and non-normal system degradations.',
      },
      {
        stage_id: 'stg-a320-5',
        stage_number: 5,
        stage_name: 'Phase 3: DGCA CA-40 Pilot Proficiency Skill Test',
        stage_type: 'SKILL_TEST_CHECK',
        ground_hours: 0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 4.0,
        has_exam_or_check: true,
        passing_score_percent: 90,
        requires_stage_cleared_to_proceed: true,
        description: 'Final license endorsement check conducted by a DGCA Synthetic Flight Examiner (SFE) covering Day & Night CA-40 test profiles.',
      },
    ],
  },
  {
    id: 'crs-a320-transition',
    course_code: 'TR-A320-TRANSITION',
    course_title: 'Airbus A320 Transition Fast-Track (For B737/ATR TR Holders — No MCC/JIT)',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    target_audience: 'TYPE_RATED_TRANSITION',
    has_mcc_jit: false,
    mcc_jit_hours: 0,
    total_ground_hours: 40.0,
    total_ftd_hours: 12.0,
    total_ffs_hours: 28.0,
    total_course_hours: 80.0,
    estimated_duration_days: 42,
    description: 'Fast-track transition type rating syllabus for experienced airline pilots with prior commercial multi-pilot jet/turboprop type rating. MCC/JIT is waived; focuses directly on fly-by-wire cross-crew qualification (CCQ), MCDU logic, and FFS profiles.',
    is_active: true,
    stages: [
      {
        stage_id: 'stg-a320t-1',
        stage_number: 1,
        stage_name: 'Phase 1: Accelerated Technical Ground School',
        stage_type: 'GROUND_THEORY',
        ground_hours: 40.0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 0,
        has_exam_or_check: true,
        passing_score_percent: 80,
        requires_stage_cleared_to_proceed: true,
        description: 'Streamlined aircraft technical systems syllabus covering FBW flight control laws, ECAM discipline, FMGS architecture, and abnormal operations.',
      },
      {
        stage_id: 'stg-a320t-2',
        stage_number: 2,
        stage_name: 'Phase 2A: FTD Level 2 SOPs & Fly-By-Wire Transition',
        stage_type: 'FTD_PROCEDURES',
        ground_hours: 0,
        sim_ftd_hours: 12.0,
        sim_ffs_hours: 0,
        has_exam_or_check: false,
        passing_score_percent: 80,
        requires_stage_cleared_to_proceed: true,
        description: 'Cockpit transition flows, Sidestick handling, and ECAM management procedures.',
      },
      {
        stage_id: 'stg-a320t-3',
        stage_number: 3,
        stage_name: 'Phase 2B: Full Flight Simulator Profiles (FFS-01 to 06)',
        stage_type: 'FFS_FULL_SIM',
        ground_hours: 0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 24.0,
        has_exam_or_check: true,
        passing_score_percent: 85,
        requires_stage_cleared_to_proceed: true,
        description: 'Manoeuvres training, engine-out approaches, TCAS RA, and abnormal procedures.',
      },
      {
        stage_id: 'stg-a320t-4',
        stage_number: 4,
        stage_name: 'Phase 3: CA-40 Skill Test & Instrument Rating Check',
        stage_type: 'SKILL_TEST_CHECK',
        ground_hours: 0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 4.0,
        has_exam_or_check: true,
        passing_score_percent: 90,
        requires_stage_cleared_to_proceed: true,
        description: 'Final Designated Examiner skill check on Level D FFS.',
      },
    ],
  },
  {
    id: 'crs-b737-initial',
    course_code: 'TR-B737-INITIAL',
    course_title: 'Boeing 737 NG/MAX Initial Type Rating (with MCC/JIT)',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    target_audience: 'FRESHER_AB_INITIO',
    has_mcc_jit: true,
    mcc_jit_hours: 20.0,
    total_ground_hours: 76.0,
    total_ftd_hours: 16.0,
    total_ffs_hours: 36.0,
    total_course_hours: 148.0,
    estimated_duration_days: 72,
    description: 'Comprehensive initial B737 Type Rating for CPL holders with Boeing dual FMC training, dual HUD operations, and CA-40 skill tests.',
    is_active: true,
    stages: [
      {
        stage_id: 'stg-b737-1',
        stage_number: 1,
        stage_name: 'Phase 1: B737 Technical Systems & Flight Planning',
        stage_type: 'GROUND_THEORY',
        ground_hours: 76.0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 0,
        has_exam_or_check: true,
        passing_score_percent: 80,
        requires_stage_cleared_to_proceed: true,
        description: 'CFM56/LEAP-1B engines, hydraulic systems A/B/Standby, electrical distribution, pressurization, QRH non-normal procedures, and weight & balance.',
      },
      {
        stage_id: 'stg-b737-2',
        stage_number: 2,
        stage_name: 'Phase 1C: Jet Induction & Multi-Crew Cooperation (MCC/JIT)',
        stage_type: 'MCC_JIT',
        ground_hours: 0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 20.0,
        has_exam_or_check: true,
        passing_score_percent: 85,
        requires_stage_cleared_to_proceed: true,
        description: 'Boeing standard flight deck communication, dual FMC cross-verification, task sharing, and flight path management.',
      },
      {
        stage_id: 'stg-b737-3',
        stage_number: 3,
        stage_name: 'Phase 2A: FTD Level 2 Normal Flows & FMC Logic',
        stage_type: 'FTD_PROCEDURES',
        ground_hours: 0,
        sim_ftd_hours: 16.0,
        sim_ffs_hours: 0,
        has_exam_or_check: true,
        passing_score_percent: 85,
        requires_stage_cleared_to_proceed: true,
        description: 'Cockpit setup, pre-flight checks, MCP autoflight guidance, and non-normal QRH memory items.',
      },
      {
        stage_id: 'stg-b737-4',
        stage_number: 4,
        stage_name: 'Phase 2B: Full Flight Simulator Level D Profiles (FFS-01 to 08)',
        stage_type: 'FFS_FULL_SIM',
        ground_hours: 0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 32.0,
        has_exam_or_check: true,
        passing_score_percent: 85,
        requires_stage_cleared_to_proceed: true,
        description: 'Crosswind landings, engine failures, manual reversion flight controls, runaway stabilizer drill, and low visibility takeoffs.',
      },
      {
        stage_id: 'stg-b737-5',
        stage_number: 5,
        stage_name: 'Phase 3: DGCA CA-40 Pilot Proficiency Skill Test',
        stage_type: 'SKILL_TEST_CHECK',
        ground_hours: 0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 4.0,
        has_exam_or_check: true,
        passing_score_percent: 90,
        requires_stage_cleared_to_proceed: true,
        description: 'Final license endorsement check with designated SFE.',
      },
    ],
  },
  {
    id: 'crs-uprt-adv',
    course_code: 'UPRT-ADVANCED',
    course_title: 'Advanced Jet Upset Prevention & Recovery Training (Special Course)',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    target_audience: 'SPECIAL_OPERATIONS',
    has_mcc_jit: false,
    mcc_jit_hours: 0,
    total_ground_hours: 8.0,
    total_ftd_hours: 0.0,
    total_ffs_hours: 4.0,
    total_course_hours: 12.0,
    estimated_duration_days: 7,
    description: 'Specialized DGCA CAR Section 8 compliance course covering aerodynamics of stalls, wake vortex encounters, high-altitude engine stalls, spatial disorientation, and nose-high / nose-low upset recovery techniques in Level D FFS.',
    is_active: true,
    stages: [
      {
        stage_id: 'stg-uprt-1',
        stage_number: 1,
        stage_name: 'Phase 1: Aerodynamics & Energy Management Theory',
        stage_type: 'GROUND_THEORY',
        ground_hours: 8.0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 0,
        has_exam_or_check: true,
        passing_score_percent: 85,
        requires_stage_cleared_to_proceed: true,
        description: 'Energy state awareness, high-altitude aerodynamics, coffin corner, Dutch roll, and human factors.',
      },
      {
        stage_id: 'stg-uprt-2',
        stage_number: 2,
        stage_name: 'Phase 2: FFS Level D Dynamic Recovery Exercises',
        stage_type: 'FFS_FULL_SIM',
        ground_hours: 0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 4.0,
        has_exam_or_check: true,
        passing_score_percent: 90,
        requires_stage_cleared_to_proceed: true,
        description: 'Full-motion simulator upset recoveries: spiral dive, pitch-up trim runaway, wake vortex roll, and sub-stall recovery.',
      },
    ],
  },
  {
    id: 'crs-cmd-upgrade',
    course_code: 'A320-COMMAND-UPGRADE',
    course_title: 'Airbus A320 Captain Command Upgrade & LHS Standardization',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    target_audience: 'CAPTAIN_UPGRADE',
    has_mcc_jit: false,
    mcc_jit_hours: 0,
    total_ground_hours: 24.0,
    total_ftd_hours: 8.0,
    total_ffs_hours: 20.0,
    total_course_hours: 52.0,
    estimated_duration_days: 28,
    description: 'Airline First Officer to Captain upgrade syllabus. Focuses on left-hand seat (LHS) tactical decision-making, emergency command authority, fuel diversions, crew incapacitation, and Category III autolands.',
    is_active: true,
    stages: [
      {
        stage_id: 'stg-cmd-1',
        stage_number: 1,
        stage_name: 'Phase 1: Command Leadership & Operational Regulations',
        stage_type: 'GROUND_THEORY',
        ground_hours: 24.0,
        sim_ftd_hours: 0,
        sim_ffs_hours: 0,
        has_exam_or_check: true,
        passing_score_percent: 85,
        requires_stage_cleared_to_proceed: true,
        description: 'Command leadership, weather minimums, fuel management, diversion strategy, and crew management.',
      },
      {
        stage_id: 'stg-cmd-2',
        stage_number: 2,
        stage_name: 'Phase 2: Left-Hand Seat FFS Simulator Scenarios',
        stage_type: 'FFS_FULL_SIM',
        ground_hours: 0,
        sim_ftd_hours: 8.0,
        sim_ffs_hours: 20.0,
        has_exam_or_check: true,
        passing_score_percent: 90,
        requires_stage_cleared_to_proceed: true,
        description: 'LOFT (Line-Oriented Flight Training) scenarios, complex dual-failure management, emergency passenger decompression, and CAT IIIB autoland rollout.',
      },
    ],
  },
];

export const ATO_BATCHES: TrainingBatch[] = [
  {
    id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    batch_name: 'IndiGo Cadet A320 Type Rating Batch 26A',
    airline_operator: 'IndiGo Airlines',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    course_id: 'crs-a320-initial',
    course_name: 'A320 Initial Type Rating (with MCC/JIT)',
    start_date: '2026-07-01',
    expected_completion_date: '2026-09-30',
    current_phase: 'SIM_FFS',
    progress_percentage: 65,
    students_count: 4,
    status: 'SIM_IN_PROGRESS',
  },
  {
    id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    batch_name: 'Air India Express B737 NG/MAX Batch 26B',
    airline_operator: 'Air India Express',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    course_id: 'crs-b737-initial',
    course_name: 'B737 Initial Type Rating (with MCC/JIT)',
    start_date: '2026-08-10',
    expected_completion_date: '2026-11-15',
    current_phase: 'GROUND_TECH',
    progress_percentage: 20,
    students_count: 4,
    status: 'ACTIVE',
  },
  {
    id: 'batch-26c',
    batch_code: 'ALLIANCE-ATR-26C',
    batch_name: 'Alliance Air ATR 72-600 Transition Batch 26C',
    airline_operator: 'Alliance Air',
    aircraft_type_id: 'fleet-atr72',
    aircraft_type_name: 'ATR 72-600',
    course_id: 'crs-a320-transition',
    course_name: 'ATR Transition Fast-Track',
    start_date: '2026-07-15',
    expected_completion_date: '2026-10-15',
    current_phase: 'SIM_FFS',
    progress_percentage: 50,
    students_count: 2,
    status: 'SIM_IN_PROGRESS',
  },
  {
    id: 'batch-26d',
    batch_code: 'SPICE-Q400-26D',
    batch_name: 'SpiceJet DHC-8 Q400 Special TR Batch 26D',
    airline_operator: 'SpiceJet',
    aircraft_type_id: 'fleet-q400',
    aircraft_type_name: 'DHC-8 Q400',
    course_id: 'crs-a320-initial',
    course_name: 'Q400 Initial Syllabus',
    start_date: '2026-08-18',
    expected_completion_date: '2026-11-30',
    current_phase: 'GROUND_PERF',
    progress_percentage: 30,
    students_count: 2,
    status: 'ACTIVE',
  },
];

export const ATO_STUDENTS: CadetStudent[] = [
  {
    id: 'stu-01',
    student_number: 'CADET-26A-01',
    full_name: 'Aditi Rao',
    avatar_initials: 'AR',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    airline_sponsor: 'IndiGo Airlines',
    airline: 'IndiGo Airlines',
    enrolled_course_id: 'crs-a320-initial',
    enrolled_course_title: 'A320 Initial (with MCC/JIT)',
    current_stage_id: 'STAGE-4-FFS',
    current_stage_name: 'Level D Full Flight Simulator Phase',
    progress_percentage: 65,
    ground_hours_completed: 72.0,
    sim_ftd_hours_completed: 16.0,
    sim_ffs_hours_completed: 16.0,
    sim_hours_completed: 16.0,
    ground_tech_completed: true,
    ground_perf_completed: true,
    mcc_jit_completed: true,
    skill_test_cleared: false,
    has_missed_sessions: false,
    missed_sessions_count: 0,
    remedial_hours_assigned: 0,
    go_no_go_status: 'GO_CLEARED',
    status: 'GROUND_CLEARED',
  },
  {
    id: 'stu-02',
    student_number: 'CADET-26A-02',
    full_name: 'Rohan Verma',
    avatar_initials: 'RV',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    airline_sponsor: 'IndiGo Airlines',
    airline: 'IndiGo Airlines',
    enrolled_course_id: 'crs-a320-initial',
    enrolled_course_title: 'A320 Initial (with MCC/JIT)',
    current_stage_id: 'STAGE-4-FFS',
    current_stage_name: 'Level D Full Flight Simulator Phase',
    progress_percentage: 65,
    ground_hours_completed: 72.0,
    sim_ftd_hours_completed: 16.0,
    sim_ffs_hours_completed: 16.0,
    sim_hours_completed: 16.0,
    ground_tech_completed: true,
    ground_perf_completed: true,
    mcc_jit_completed: true,
    skill_test_cleared: false,
    has_missed_sessions: false,
    missed_sessions_count: 0,
    remedial_hours_assigned: 0,
    go_no_go_status: 'GO_CLEARED',
    status: 'GROUND_CLEARED',
  },
  {
    id: 'stu-03',
    student_number: 'CADET-26B-01',
    full_name: 'Tanya Sen',
    avatar_initials: 'TS',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    airline_sponsor: 'Air India Express',
    airline: 'Air India Express',
    enrolled_course_id: 'crs-b737-initial',
    enrolled_course_title: 'B737 Initial (with MCC/JIT)',
    current_stage_id: 'STAGE-1-GROUND',
    current_stage_name: 'Ground Theory & Systems',
    progress_percentage: 20,
    ground_hours_completed: 16.0,
    sim_ftd_hours_completed: 0,
    sim_ffs_hours_completed: 0,
    sim_hours_completed: 0,
    ground_tech_completed: false,
    ground_perf_completed: false,
    mcc_jit_completed: false,
    skill_test_cleared: false,
    has_missed_sessions: true,
    missed_sessions_count: 1,
    remedial_hours_assigned: 0,
    go_no_go_status: 'NO_GO_BLOCKED',
    blocker_reason: 'MISSED SESSION: Missed GND-TECH-01 (Hydraulics & Airframe). Blocked from booking simulator until makeup class is completed.',
    status: 'IN_TRAINING',
  },
  {
    id: 'stu-04',
    student_number: 'CADET-26B-02',
    full_name: 'Siddharth Nair',
    avatar_initials: 'SN',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    airline_sponsor: 'Air India Express',
    airline: 'Air India Express',
    enrolled_course_id: 'crs-b737-initial',
    enrolled_course_title: 'B737 Initial (with MCC/JIT)',
    current_stage_id: 'STAGE-1-GROUND',
    current_stage_name: 'Ground Theory & Systems',
    progress_percentage: 20,
    ground_hours_completed: 20.0,
    sim_ftd_hours_completed: 0,
    sim_ffs_hours_completed: 0,
    sim_hours_completed: 0,
    ground_tech_completed: false,
    ground_perf_completed: false,
    mcc_jit_completed: false,
    skill_test_cleared: false,
    has_missed_sessions: false,
    missed_sessions_count: 0,
    remedial_hours_assigned: 0,
    go_no_go_status: 'GO_CLEARED',
    status: 'IN_TRAINING',
  },
  {
    id: 'stu-05',
    student_number: 'CADET-26C-01',
    full_name: 'Manish Pandey',
    avatar_initials: 'MP',
    batch_id: 'batch-26c',
    batch_code: 'ALLIANCE-ATR-26C',
    airline_sponsor: 'Alliance Air',
    airline: 'Alliance Air',
    enrolled_course_id: 'crs-a320-transition',
    enrolled_course_title: 'ATR Transition Fast-Track (No MCC/JIT)',
    current_stage_id: 'STAGE-3-FFS-FAST',
    current_stage_name: 'Simulator Progress Assessment',
    progress_percentage: 50,
    ground_hours_completed: 40.0,
    sim_ftd_hours_completed: 12.0,
    sim_ffs_hours_completed: 12.0,
    sim_hours_completed: 12.0,
    ground_tech_completed: true,
    ground_perf_completed: true,
    mcc_jit_completed: true,
    skill_test_cleared: false,
    has_missed_sessions: false,
    missed_sessions_count: 0,
    remedial_hours_assigned: 2.0,
    go_no_go_status: 'REMEDIAL_ACTIVE',
    blocker_reason: 'REMEDIAL MANDATED: 2.0h remedial assigned for single-engine go-around rudder coordination before skill check.',
    status: 'GROUND_CLEARED',
  },
  {
    id: 'stu-06',
    student_number: 'CADET-26D-01',
    full_name: 'Pooja Hegde',
    avatar_initials: 'PH',
    batch_id: 'batch-26d',
    batch_code: 'SPICE-Q400-26D',
    airline_sponsor: 'SpiceJet',
    airline: 'SpiceJet',
    enrolled_course_id: 'crs-a320-initial',
    enrolled_course_title: 'Q400 Initial Syllabus',
    current_stage_id: 'STAGE-1-GROUND',
    current_stage_name: 'Ground Theory & Systems',
    progress_percentage: 30,
    ground_hours_completed: 24.0,
    sim_ftd_hours_completed: 0,
    sim_ffs_hours_completed: 0,
    sim_hours_completed: 0,
    ground_tech_completed: true,
    ground_perf_completed: false,
    mcc_jit_completed: false,
    skill_test_cleared: false,
    has_missed_sessions: false,
    missed_sessions_count: 0,
    remedial_hours_assigned: 0,
    go_no_go_status: 'GO_CLEARED',
    status: 'IN_TRAINING',
  },
];

export const ATO_INSTRUCTORS: InstructorProfile[] = [
  // 1. Technical Ground Instructor
  {
    id: 'ins-tech-gi',
    staff_id: 'GI-TECH-001',
    full_name: 'Capt. Hemant Kulkarni',
    email: 'hemant.kulkarni@gata.aero',
    phone: '+91 98201 11223',
    roles: ['GI_TECH', 'GI_PERF'],
    assigned_fleets: ['A320', 'B737', 'ATR 72-600', 'Q400'],
    qualifications: [
      {
        id: 'qual-hk-01',
        fleet_code: 'ALL_FLEETS',
        role: 'GI_TECH',
        approval_number: 'DGCA/GI/TECH/4091',
        approval_type: 'GI CAR Section 7 (Technical Systems & Airframe)',
        approval_issue_date: '2023-04-15',
        approval_expiry_date: '2028-04-14',
        base_month: 'April',
        recurrent_expiry: '2027-04-30',
        recurrent_window_start: '2027-02-01',
        status: 'VALID',
      },
      {
        id: 'qual-hk-02',
        fleet_code: 'ALL_FLEETS',
        role: 'GI_PERF',
        approval_number: 'DGCA/GI/PERF/4092',
        approval_type: 'GI CAR Section 7 (Performance & Flight Planning)',
        approval_issue_date: '2024-01-20',
        approval_expiry_date: '2029-01-19',
        base_month: 'January',
        recurrent_expiry: '2027-01-31',
        recurrent_window_start: '2026-11-01',
        status: 'VALID',
      },
    ],
    dgca_approval_number: 'DGCA/GI/TECH/4091',
    dgca_approval_type: 'GI CAR Section 7 (Technical Systems)',
    dgca_5yr_approval_issue: '2023-04-15',
    dgca_5yr_approval_expiry: '2028-04-14',
    base_month: 'April',
    recurrent_expiry: '2027-04-30',
    recurrent_window_start: '2027-02-01',
    recurrent_status: 'VALID',
    employment_status: 'ACTIVE',
    currency_status: 'VALID',
    is_locked_out: false,
    avatar_initials: 'HK',
  },

  // 2. Performance / SME Ground Instructor
  {
    id: 'ins-perf-gi',
    staff_id: 'GI-PERF-002',
    full_name: 'Capt. Sanjay Deshmukh',
    email: 'sanjay.deshmukh@gata.aero',
    phone: '+91 98202 22334',
    roles: ['GI_PERF'],
    assigned_fleets: ['A320', 'B737', 'ATR 72-600', 'Q400'],
    qualifications: [
      {
        id: 'qual-sd-01',
        fleet_code: 'ALL_FLEETS',
        role: 'GI_PERF',
        approval_number: 'DGCA/GI/PERF/5102',
        approval_type: 'GI CAR Section 7 (Performance & W&B)',
        approval_issue_date: '2023-08-01',
        approval_expiry_date: '2028-07-31',
        base_month: 'August',
        recurrent_expiry: '2027-08-31',
        recurrent_window_start: '2027-06-01',
        status: 'VALID',
      },
    ],
    dgca_approval_number: 'DGCA/GI/PERF/5102',
    dgca_approval_type: 'GI CAR Section 7 (Performance & W&B)',
    dgca_5yr_approval_issue: '2023-08-01',
    dgca_5yr_approval_expiry: '2028-07-31',
    base_month: 'August',
    recurrent_expiry: '2027-08-31',
    recurrent_window_start: '2027-06-01',
    recurrent_status: 'VALID',
    employment_status: 'ACTIVE',
    currency_status: 'VALID',
    is_locked_out: false,
    avatar_initials: 'SD',
  },

  // 3. SFI / SFE - Multi-Type: Airbus A320 & Boeing 737
  {
    id: 'ins-sfi-a320',
    staff_id: 'SFI-A320-201',
    full_name: 'Capt. Rahul Sharma',
    email: 'rahul.sharma@gata.aero',
    phone: '+91 98111 22334',
    roles: ['SFI', 'SFE'],
    assigned_fleets: ['A320', 'B737'],
    qualifications: [
      {
        id: 'qual-rs-01',
        fleet_code: 'A320',
        role: 'SFI',
        approval_number: 'DGCA/SFI/A320/8812',
        approval_type: 'SFI CAR Section 7 (Level D FFS)',
        approval_issue_date: '2024-06-10',
        approval_expiry_date: '2029-06-09',
        base_month: 'June',
        recurrent_expiry: '2027-06-30',
        recurrent_window_start: '2027-04-01',
        status: 'VALID',
      },
      {
        id: 'qual-rs-02',
        fleet_code: 'A320',
        role: 'SFE',
        approval_number: 'DGCA/SFE/A320/8812-EXAM',
        approval_type: 'SFE CAR Section 7 (Designated Examiner CA-40)',
        approval_issue_date: '2024-06-10',
        approval_expiry_date: '2029-06-09',
        base_month: 'June',
        recurrent_expiry: '2027-06-30',
        recurrent_window_start: '2027-04-01',
        status: 'VALID',
      },
      {
        id: 'qual-rs-03',
        fleet_code: 'B737',
        role: 'SFI',
        approval_number: 'DGCA/SFI/B737/4109',
        approval_type: 'SFI CAR Section 7 (Level D FFS)',
        approval_issue_date: '2023-11-15',
        approval_expiry_date: '2028-11-14',
        base_month: 'November',
        recurrent_expiry: '2026-11-30',
        recurrent_window_start: '2026-09-01',
        status: 'VALID',
      },
    ],
    dgca_approval_number: 'DGCA/SFI/A320/8812',
    dgca_approval_type: 'SFI / SFE CAR (Level D FFS)',
    dgca_5yr_approval_issue: '2024-06-10',
    dgca_5yr_approval_expiry: '2029-06-09',
    base_month: 'June',
    recurrent_expiry: '2027-06-30',
    recurrent_window_start: '2027-04-01',
    recurrent_status: 'VALID',
    employment_status: 'ACTIVE',
    currency_status: 'VALID',
    is_locked_out: false,
    avatar_initials: 'RS',
  },

  // 4. SFI - Boeing 737 NG/MAX
  {
    id: 'ins-sfi-b737',
    staff_id: 'SFI-B737-202',
    full_name: 'Capt. Sarah Jenkins',
    email: 'sarah.jenkins@gata.aero',
    phone: '+91 98222 33445',
    roles: ['SFI'],
    assigned_fleets: ['B737'],
    qualifications: [
      {
        id: 'qual-sj-01',
        fleet_code: 'B737',
        role: 'SFI',
        approval_number: 'DGCA/SFI/B737/9011',
        approval_type: 'SFI CAR (Level D)',
        approval_issue_date: '2024-03-01',
        approval_expiry_date: '2029-02-28',
        base_month: 'March',
        recurrent_expiry: '2027-03-31',
        recurrent_window_start: '2027-01-01',
        status: 'VALID',
      },
    ],
    dgca_approval_number: 'DGCA/SFI/B737/9011',
    dgca_approval_type: 'SFI CAR (Level D)',
    dgca_5yr_approval_issue: '2024-03-01',
    dgca_5yr_approval_expiry: '2029-02-28',
    base_month: 'March',
    recurrent_expiry: '2027-03-31',
    recurrent_window_start: '2027-01-01',
    recurrent_status: 'VALID',
    employment_status: 'ACTIVE',
    currency_status: 'VALID',
    is_locked_out: false,
    avatar_initials: 'SJ',
  },

  // 5. SFI - Turboprop (ATR 72-600 & Q400) - Inside 3-Month Recurrent Window!
  {
    id: 'ins-sfi-turbo',
    staff_id: 'SFI-TURBO-203',
    full_name: 'Capt. Vikram Mehra',
    email: 'vikram.mehra@gata.aero',
    phone: '+91 98333 44556',
    roles: ['SFI'],
    assigned_fleets: ['ATR 72-600', 'Q400'],
    qualifications: [
      {
        id: 'qual-vm-01',
        fleet_code: 'ATR 72-600',
        role: 'SFI',
        approval_number: 'DGCA/SFI/ATR/7311',
        approval_type: 'SFI CAR (Level D)',
        approval_issue_date: '2022-09-15',
        approval_expiry_date: '2027-09-14',
        base_month: 'September',
        recurrent_expiry: '2026-09-15',
        recurrent_window_start: '2026-06-15',
        status: 'EXPIRING',
      },
      {
        id: 'qual-vm-02',
        fleet_code: 'Q400',
        role: 'SFI',
        approval_number: 'DGCA/SFI/Q400/7312',
        approval_type: 'SFI CAR (Level D)',
        approval_issue_date: '2024-02-10',
        approval_expiry_date: '2029-02-09',
        base_month: 'February',
        recurrent_expiry: '2027-02-28',
        recurrent_window_start: '2026-12-01',
        status: 'VALID',
      },
    ],
    dgca_approval_number: 'DGCA/SFI/ATR/7311',
    dgca_approval_type: 'SFI CAR (Level D)',
    dgca_5yr_approval_issue: '2022-09-15',
    dgca_5yr_approval_expiry: '2027-09-14',
    base_month: 'September',
    recurrent_expiry: '2026-09-15',
    recurrent_window_start: '2026-06-15',
    recurrent_status: 'EXPIRING',
    employment_status: 'ACTIVE',
    currency_status: 'VALID',
    is_locked_out: false,
    lockout_reason: 'Inside 3-Month TRS Recurrent Renewal Window (Expires 15 Sep 2026)',
    avatar_initials: 'VM',
  },

  // 6. SFI - A320 with High FDTL (Near 24h & 7d limits)
  {
    id: 'ins-sfi-high-fdtl',
    staff_id: 'SFI-A320-204',
    full_name: 'Capt. Rajesh Gupta',
    email: 'rajesh.gupta@gata.aero',
    phone: '+91 98444 55667',
    roles: ['SFI'],
    assigned_fleets: ['A320', 'B737', 'ATR 72-600', 'Q400'],
    qualifications: [
      {
        id: 'qual-rg-01',
        fleet_code: 'A320',
        role: 'SFI',
        approval_number: 'DGCA/SFI/A320/6654',
        approval_type: 'SFI CAR (Level D)',
        approval_issue_date: '2023-01-10',
        approval_expiry_date: '2028-01-09',
        base_month: 'January',
        recurrent_expiry: '2027-01-31',
        recurrent_window_start: '2026-11-01',
        status: 'VALID',
      },
      {
        id: 'qual-rg-02',
        fleet_code: 'B737',
        role: 'SFI',
        approval_number: 'DGCA/SFI/B737/6655',
        approval_type: 'SFI CAR (Level D)',
        approval_issue_date: '2023-05-12',
        approval_expiry_date: '2028-05-11',
        base_month: 'May',
        recurrent_expiry: '2027-05-31',
        recurrent_window_start: '2027-03-01',
        status: 'VALID',
      },
    ],
    dgca_approval_number: 'DGCA/SFI/A320/6654',
    dgca_approval_type: 'SFI CAR (Level D)',
    dgca_5yr_approval_issue: '2023-01-10',
    dgca_5yr_approval_expiry: '2028-01-09',
    base_month: 'January',
    recurrent_expiry: '2027-01-31',
    recurrent_window_start: '2026-11-01',
    recurrent_status: 'VALID',
    employment_status: 'ACTIVE',
    currency_status: 'VALID',
    is_locked_out: false,
    lockout_reason: 'Approaching DGCA CAR duty limits (5.5h / 6.0h in 24h; 28.0h / 30.0h in 7d)',
    avatar_initials: 'RG',
  },

  // 7. SFE (Synthetic Flight Examiner - A320/B737)
  {
    id: 'ins-sfe-chief',
    staff_id: 'SFE-CHIEF-301',
    full_name: 'Capt. Arun Kapur',
    email: 'arun.kapur@gata.aero',
    phone: '+91 98555 11223',
    roles: ['SFE', 'SFI'],
    assigned_fleets: ['A320', 'B737'],
    qualifications: [
      {
        id: 'qual-ak-01',
        fleet_code: 'A320',
        role: 'SFE',
        approval_number: 'DGCA/SFE/A320/1001',
        approval_type: 'SFE CAR (Designated Examiner)',
        approval_issue_date: '2024-01-05',
        approval_expiry_date: '2029-01-04',
        base_month: 'January',
        recurrent_expiry: '2027-01-31',
        recurrent_window_start: '2026-11-01',
        status: 'VALID',
      },
      {
        id: 'qual-ak-02',
        fleet_code: 'B737',
        role: 'SFE',
        approval_number: 'DGCA/SFE/B737/1002',
        approval_type: 'SFE CAR (Designated Examiner)',
        approval_issue_date: '2024-01-05',
        approval_expiry_date: '2029-01-04',
        base_month: 'January',
        recurrent_expiry: '2027-01-31',
        recurrent_window_start: '2026-11-01',
        status: 'VALID',
      },
    ],
    dgca_approval_number: 'DGCA/SFE/ALL/1001',
    dgca_approval_type: 'SFE CAR (Designated Examiner)',
    dgca_5yr_approval_issue: '2024-01-05',
    dgca_5yr_approval_expiry: '2029-01-04',
    base_month: 'January',
    recurrent_expiry: '2027-01-31',
    recurrent_window_start: '2026-11-01',
    recurrent_status: 'VALID',
    employment_status: 'ACTIVE',
    currency_status: 'VALID',
    is_locked_out: false,
    avatar_initials: 'AK',
  },

  // 8. SFE - Missed Recurrent -> Status: REFRESHER_REQUIRED Lockout
  {
    id: 'ins-sfe-locked',
    staff_id: 'SFE-A320-302',
    full_name: 'Capt. Elena Rostova',
    email: 'elena.rostova@gata.aero',
    phone: '+91 98666 99887',
    roles: ['SFE', 'SFI'],
    assigned_fleets: ['A320'],
    qualifications: [
      {
        id: 'qual-er-01',
        fleet_code: 'A320',
        role: 'SFE',
        approval_number: 'DGCA/SFE/A320/2209',
        approval_type: 'SFE CAR (Designated Examiner)',
        approval_issue_date: '2020-04-10',
        approval_expiry_date: '2025-04-09',
        base_month: 'April',
        recurrent_expiry: '2026-04-30',
        recurrent_window_start: '2026-02-01',
        status: 'REFRESHER_REQUIRED',
      },
    ],
    dgca_approval_number: 'DGCA/SFE/A320/2209',
    dgca_approval_type: 'SFE CAR (Designated Examiner)',
    dgca_5yr_approval_issue: '2020-04-10',
    dgca_5yr_approval_expiry: '2025-04-09',
    base_month: 'April',
    recurrent_expiry: '2026-04-30',
    recurrent_window_start: '2026-02-01',
    recurrent_status: 'REFRESHER_REQUIRED',
    employment_status: 'ACTIVE',
    currency_status: 'EXPIRED',
    is_locked_out: true,
    lockout_reason: 'REFRESHER REQUIRED: 1-Year TRS Recurrent Check missed. Auto-locked out by DGCA CAR mandate.',
    avatar_initials: 'ER',
  },
];

export const ATO_SIMULATORS: SimulatorResource[] = [
  {
    id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    resource_category: 'FFS',
    level: 'Level D (Full Motion)',
    supported_aircraft_ids: ['fleet-a320'],
    supported_aircraft_names: ['Airbus A320 CEO', 'Airbus A320 NEO'],
    status: 'AVAILABLE',
    bay_location: 'Sim Bay 1 (CAE 7000XR)',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/FSTD/A320/019',
    approval_expiry: '2027-12-31',
  },
  {
    id: 'sim-b737-01',
    resource_name: 'B737 FFS-01',
    resource_category: 'FFS',
    level: 'Level D (Full Motion)',
    supported_aircraft_ids: ['fleet-b737'],
    supported_aircraft_names: ['Boeing B737 NG', 'Boeing B737 MAX'],
    status: 'AVAILABLE',
    bay_location: 'Sim Bay 2 (L3Harris RealitySeven)',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/FSTD/B737/022',
    approval_expiry: '2027-03-15',
  },
  {
    id: 'sim-atr72-01',
    resource_name: 'ATR 72-600 FFS-01',
    resource_category: 'FFS',
    level: 'Level D (Full Motion)',
    supported_aircraft_ids: ['fleet-atr72'],
    supported_aircraft_names: ['ATR 72-600'],
    status: 'AVAILABLE',
    bay_location: 'Sim Bay 3 (Thales Reality)',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/FSTD/ATR/008',
    approval_expiry: '2027-08-30',
  },
  {
    id: 'sim-q400-01',
    resource_name: 'Q400 FFS-01',
    resource_category: 'FFS',
    level: 'Level D (Full Motion)',
    supported_aircraft_ids: ['fleet-q400'],
    supported_aircraft_names: ['DHC-8 Q400'],
    status: 'AVAILABLE',
    bay_location: 'Sim Bay 4 (FlightSafety Int.)',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/FSTD/Q400/012',
    approval_expiry: '2027-10-15',
  },
  {
    id: 'sim-a320-ftd',
    resource_name: 'A320 FTD-01',
    resource_category: 'FTD',
    level: 'Level 2 (Fixed Base)',
    supported_aircraft_ids: ['fleet-a320'],
    supported_aircraft_names: ['Airbus A320 CEO'],
    status: 'AVAILABLE',
    bay_location: 'FTD Procedural Lab 1',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/FTD/A320/004',
    approval_expiry: '2026-12-31',
  },
  {
    id: 'room-alpha',
    resource_name: 'Classroom Alpha (Systems & Tech)',
    resource_category: 'CLASSROOM',
    level: '24-Seat Interactive CBT Lab',
    supported_aircraft_ids: ['fleet-a320', 'fleet-b737', 'fleet-atr72', 'fleet-q400'],
    supported_aircraft_names: ['All Fleets'],
    status: 'AVAILABLE',
    bay_location: 'Academic Wing Level 2',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/CLASS/01',
    approval_expiry: '2028-12-31',
  },
  {
    id: 'room-beta',
    resource_name: 'Classroom Beta (Performance & Flight Planning)',
    resource_category: 'CLASSROOM',
    level: '18-Seat Flight Planning Hub',
    supported_aircraft_ids: ['fleet-a320', 'fleet-b737', 'fleet-atr72', 'fleet-q400'],
    supported_aircraft_names: ['All Fleets'],
    status: 'AVAILABLE',
    bay_location: 'Academic Wing Level 2',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/CLASS/02',
    approval_expiry: '2028-12-31',
  },
];

export const ATO_SYLLABUS: CourseSyllabusItem[] = [
  // Phase 1A: Technical Ground School (Conducted by Tech GI)
  {
    id: 'syl-gnd-tech-01',
    aircraft_type_id: 'fleet-a320',
    phase: 'GROUND_TECH',
    session_code: 'GND-TECH-01',
    session_title: 'Aircraft Systems, Airframe & Electrics/Hydraulics',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 0.0,
    total_duty_hours: 4.0,
    required_instructor_role: 'GI_TECH',
    required_resource_category: 'CLASSROOM',
    is_check: false,
    description: 'Comprehensive systems walkthrough conducted by Technical Ground Instructor (Tech GI)',
  },
  {
    id: 'syl-gnd-tech-02',
    aircraft_type_id: 'fleet-a320',
    phase: 'GROUND_TECH',
    session_code: 'GND-TECH-02',
    session_title: 'Avionics, Autoflight, FMS & Powerplant Systems',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 0.0,
    total_duty_hours: 4.0,
    required_instructor_role: 'GI_TECH',
    required_resource_category: 'CLASSROOM',
    is_check: false,
    description: 'FMS logic and autoflight modes technical lecture',
  },

  // Phase 1B: Performance & W&B Ground School (Conducted by Perf GI / SME)
  {
    id: 'syl-gnd-perf-01',
    aircraft_type_id: 'fleet-a320',
    phase: 'GROUND_PERF',
    session_code: 'GND-PERF-01',
    session_title: 'Takeoff & Landing Performance, Weight & Balance',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 0.0,
    total_duty_hours: 4.0,
    required_instructor_role: 'GI_PERF',
    required_resource_category: 'CLASSROOM',
    is_check: false,
    description: 'Speeds (V1/VR/V2), runway analysis, obstacle clearance, loadsheets conducted by Perf GI / SME',
  },
  {
    id: 'syl-gnd-perf-02',
    aircraft_type_id: 'fleet-a320',
    phase: 'GROUND_PERF',
    session_code: 'GND-PERF-02',
    session_title: 'Operational Flight Planning, Enroute Weather & ETOPS',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 0.0,
    total_duty_hours: 4.0,
    required_instructor_role: 'GI_PERF',
    required_resource_category: 'CLASSROOM',
    is_check: false,
    description: 'OFP generation, fuel planning, alternate minima and dispatch limits',
  },

  // Phase 2: Simulator Training (Conducted by SFI with 2h Briefing + 4h Sim)
  {
    id: 'syl-ftd-01',
    aircraft_type_id: 'fleet-a320',
    phase: 'SIM_FTD',
    session_code: 'FTD-01',
    session_title: 'Cockpit Standard Operating Procedures & FMS Setup',
    duration_instructional_hours: 2.0,
    duration_briefing_hours: 2.0,
    total_duty_hours: 4.0,
    required_instructor_role: 'SFI',
    required_resource_category: 'FTD',
    is_check: false,
    description: 'Fixed-base procedure trainer: Pre-flight briefing (2h) + FTD session (2h)',
  },
  {
    id: 'syl-ffs-01',
    aircraft_type_id: 'fleet-a320',
    phase: 'SIM_FFS',
    session_code: 'FFS-01',
    session_title: 'Normal Handling, Visual Circuits & Crosswind Landings',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 2.0,
    total_duty_hours: 6.0,
    required_instructor_role: 'SFI',
    required_resource_category: 'FFS',
    is_check: false,
    description: 'Level D FFS: Pre/Post-Flight Briefing (2.0h) + Sim Flight (4.0h) = 6.0h total duty',
  },
  {
    id: 'syl-ffs-04',
    aircraft_type_id: 'fleet-a320',
    phase: 'SIM_FFS',
    session_code: 'FFS-04',
    session_title: 'Engine Failure After V1, Single-Engine Approaches',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 2.0,
    total_duty_hours: 6.0,
    required_instructor_role: 'SFI',
    required_resource_category: 'FFS',
    is_check: false,
    description: 'Critical emergency profile: V1 cut, single-engine missed approach, non-precision approach',
  },
  {
    id: 'syl-ffs-08',
    aircraft_type_id: 'fleet-a320',
    phase: 'SIM_FFS',
    session_code: 'FFS-08',
    session_title: 'Line Oriented Flight Training (LOFT) & Complex ECAM',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 2.0,
    total_duty_hours: 6.0,
    required_instructor_role: 'SFI',
    required_resource_category: 'FFS',
    is_check: false,
    description: 'Full real-time scenario from Delhi (VIDP) to Mumbai (VABB) with enroute weather & dual failure',
  },

  // Phase 3: Check & Licensing (Conducted by SFE Examiner)
  {
    id: 'syl-ca40',
    aircraft_type_id: 'fleet-a320',
    phase: 'SKILL_TEST',
    session_code: 'CA-40',
    session_title: 'DGCA CA-40 Day/Night Skill Test & PPC Check',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 2.0,
    total_duty_hours: 6.0,
    required_instructor_role: 'SFE',
    required_resource_category: 'FFS',
    is_check: true,
    description: 'Final Type Rating License Endorsement Skill Test conducted by DGCA Designated Examiner (SFE)',
  },
];

export const ATO_ACTIVE_SCHEDULES: TrainingScheduleSession[] = [
  {
    id: 'sch-01',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'FFS-04',
    session_title: 'FFS-04 Single Engine Profile',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFI',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01', 'stu-02'],
    student_names: ['Aditi Rao (PF)', 'Rohan Verma (PM)'],
    date: '2026-08-25',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'COMPLETED',
  },
  {
    id: 'sch-02',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'GND-TECH-01',
    session_title: 'GND-TECH-01 Systems & Airframe',
    phase: 'GROUND_TECH',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-tech-gi',
    instructor_name: 'Capt. Hemant Kulkarni',
    instructor_role: 'GI_TECH',
    resource_id: 'room-alpha',
    resource_name: 'Classroom Alpha',
    student_ids: ['stu-03', 'stu-04'],
    student_names: ['Tanya Sen', 'Siddharth Nair'],
    date: '2026-08-25',
    start_time: '09:00',
    end_time: '13:00',
    briefing_hours: 0.0,
    sim_hours: 0.0,
    total_duty_hours: 4.0,
    status: 'COMPLETED',
  },
  {
    id: 'sch-03',
    batch_id: 'batch-26d',
    batch_code: 'SPICE-Q400-26D',
    session_code: 'GND-PERF-01',
    session_title: 'GND-PERF-01 Performance & W&B',
    phase: 'GROUND_PERF',
    aircraft_type_id: 'fleet-q400',
    aircraft_type_name: 'DHC-8 Q400',
    instructor_id: 'ins-perf-gi',
    instructor_name: 'Capt. Sanjay Deshmukh',
    instructor_role: 'GI_PERF',
    resource_id: 'room-beta',
    resource_name: 'Classroom Beta',
    student_ids: ['stu-06'],
    student_names: ['Pooja Hegde'],
    date: '2026-08-25',
    start_time: '10:00',
    end_time: '14:00',
    briefing_hours: 0.0,
    sim_hours: 0.0,
    total_duty_hours: 4.0,
    status: 'COMPLETED',
  },
  {
    id: 'sch-04',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'SKILL-TEST',
    session_title: 'CA-40 Pilot Proficiency Check (PPC)',
    phase: 'SKILL_TEST',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFE',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01'],
    student_names: ['Aditi Rao'],
    date: '2026-08-25',
    start_time: '15:00',
    end_time: '19:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'COMPLETED',
  },
  {
    id: 'sch-05',
    batch_id: 'batch-26c',
    batch_code: 'IX-ATR-26C',
    session_code: 'FTD-01',
    session_title: 'FTD-01 Normal SOPs & FMS Setup',
    phase: 'SIM_FTD',
    aircraft_type_id: 'fleet-atr72',
    aircraft_type_name: 'ATR 72-600',
    instructor_id: 'ins-sfi-high-fdtl',
    instructor_name: 'Capt. Rajesh Gupta',
    instructor_role: 'SFI',
    resource_id: 'sim-ftd-01',
    resource_name: 'Multi-Type FTD-01',
    student_ids: ['stu-05'],
    student_names: ['Alok Mehta'],
    date: '2026-08-25',
    start_time: '14:00',
    end_time: '18:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'COMPLETED',
  },
  {
    id: 'sch-06',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'FFS-05',
    session_title: 'FFS-05 Adverse Weather & Windshear',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFI',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01', 'stu-02'],
    student_names: ['Aditi Rao (PF)', 'Rohan Verma (PM)'],
    date: '2026-08-26',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'IN_PROGRESS',
  },
  {
    id: 'sch-06b',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'GND-TECH-02',
    session_title: 'GND-TECH-02 Hydraulics & Fuel Systems',
    phase: 'GROUND_TECH',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-tech-gi',
    instructor_name: 'Capt. Hemant Kulkarni',
    instructor_role: 'GI_TECH',
    resource_id: 'room-alpha',
    resource_name: 'Classroom Alpha',
    student_ids: ['stu-03', 'stu-04'],
    student_names: ['Tanya Sen', 'Siddharth Nair'],
    date: '2026-08-26',
    start_time: '09:00',
    end_time: '13:00',
    briefing_hours: 0.0,
    sim_hours: 0.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-07',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'FTD-01',
    session_title: 'FTD-01 Cockpit Flows & CDU Setup',
    phase: 'SIM_FTD',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-sfi-high-fdtl',
    instructor_name: 'Capt. Rajesh Gupta',
    instructor_role: 'SFI',
    resource_id: 'sim-ftd-01',
    resource_name: 'Multi-Type FTD-01 (Level 5)',
    student_ids: ['stu-03', 'stu-04'],
    student_names: ['Tanya Sen', 'Siddharth Nair'],
    date: '2026-08-26',
    start_time: '14:00',
    end_time: '18:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-07b',
    batch_id: 'batch-26c',
    batch_code: 'ALLIANCE-ATR-26C',
    session_code: 'FTD-02',
    session_title: 'FTD-02 Single-Engine Failure Procedures',
    phase: 'SIM_FTD',
    aircraft_type_id: 'fleet-atr72',
    aircraft_type_name: 'ATR 72-600',
    instructor_id: 'ins-sfi-atr',
    instructor_name: 'Capt. Vikram Malhotra',
    instructor_role: 'SFI',
    resource_id: 'sim-ftd-01',
    resource_name: 'Multi-Type FTD-01 (Level 5)',
    student_ids: ['stu-05'],
    student_names: ['Manish Pandey'],
    date: '2026-08-26',
    start_time: '14:00',
    end_time: '18:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-08',
    batch_id: 'batch-26c',
    batch_code: 'IX-ATR-26C',
    session_code: 'GND-TECH-01',
    session_title: 'GND-TECH-01 PW127M Engine & Electrics',
    phase: 'GROUND_TECH',
    aircraft_type_id: 'fleet-atr72',
    aircraft_type_name: 'ATR 72-600',
    instructor_id: 'ins-tech-gi',
    instructor_name: 'Capt. Hemant Kulkarni',
    instructor_role: 'GI_TECH',
    resource_id: 'room-alpha',
    resource_name: 'Classroom Alpha',
    student_ids: ['stu-05'],
    student_names: ['Alok Mehta'],
    date: '2026-08-27',
    start_time: '09:00',
    end_time: '13:00',
    briefing_hours: 0.0,
    sim_hours: 0.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-09',
    batch_id: 'batch-26d',
    batch_code: 'SPICE-Q400-26D',
    session_code: 'FTD-01',
    session_title: 'FTD-01 High-Speed Turboprop SOPs',
    phase: 'SIM_FTD',
    aircraft_type_id: 'fleet-q400',
    aircraft_type_name: 'DHC-8 Q400',
    instructor_id: 'ins-sfi-high-fdtl',
    instructor_name: 'Capt. Rajesh Gupta',
    instructor_role: 'SFI',
    resource_id: 'sim-ftd-01',
    resource_name: 'Multi-Type FTD-01',
    student_ids: ['stu-06'],
    student_names: ['Pooja Hegde'],
    date: '2026-08-27',
    start_time: '14:00',
    end_time: '18:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-10',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'FFS-06',
    session_title: 'FFS-06 Line Oriented Flight Training (LOFT)',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFI',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01', 'stu-02'],
    student_names: ['Aditi Rao (PF)', 'Rohan Verma (PM)'],
    date: '2026-08-28',
    start_time: '10:00',
    end_time: '16:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-11',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'SKILL-TEST',
    session_title: 'CA-40 Final Skill Test & PPC',
    phase: 'SKILL_TEST',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFE',
    resource_id: 'sim-b737-01',
    resource_name: 'B737 FFS-01',
    student_ids: ['stu-03'],
    student_names: ['Tanya Sen'],
    date: '2026-08-29',
    start_time: '08:00',
    end_time: '12:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-12',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'FFS-07',
    session_title: 'FFS-07 Precision ILS CAT IIIB & Autoland',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFI',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01', 'stu-02'],
    student_names: ['Aditi Rao (PF)', 'Rohan Verma (PM)'],
    date: '2026-09-02',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-13',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'FFS-04',
    session_title: 'FFS-04 Non-Precision Approaches & Go-Arounds',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-sfi-high-fdtl',
    instructor_name: 'Capt. Rajesh Gupta',
    instructor_role: 'SFI',
    resource_id: 'sim-b737-01',
    resource_name: 'B737 FFS-01',
    student_ids: ['stu-03', 'stu-04'],
    student_names: ['Tanya Sen', 'Siddharth Nair'],
    date: '2026-09-08',
    start_time: '14:00',
    end_time: '20:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-14',
    batch_id: 'batch-26c',
    batch_code: 'IX-ATR-26C',
    session_code: 'SKILL-TEST',
    session_title: 'CA-40 ATR 72-600 Skill Test',
    phase: 'SKILL_TEST',
    aircraft_type_id: 'fleet-atr72',
    aircraft_type_name: 'ATR 72-600',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFE',
    resource_id: 'sim-ftd-01',
    resource_name: 'Multi-Type FTD-01',
    student_ids: ['stu-05'],
    student_names: ['Alok Mehta'],
    date: '2026-09-15',
    start_time: '09:00',
    end_time: '13:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-15',
    batch_id: 'batch-26d',
    batch_code: 'SPICE-Q400-26D',
    session_code: 'SKILL-TEST',
    session_title: 'CA-40 Q400 Skill Endorsement',
    phase: 'SKILL_TEST',
    aircraft_type_id: 'fleet-q400',
    aircraft_type_name: 'DHC-8 Q400',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFE',
    resource_id: 'sim-ftd-01',
    resource_name: 'Multi-Type FTD-01',
    student_ids: ['stu-06'],
    student_names: ['Pooja Hegde'],
    date: '2026-10-12',
    start_time: '10:00',
    end_time: '14:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-16',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'FFS-08',
    session_title: 'FFS-08 Annual Recurrent & PPC Refresher',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFI',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01', 'stu-02'],
    student_names: ['Aditi Rao', 'Rohan Verma'],
    date: '2026-11-20',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-17',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'FFS-08',
    session_title: 'FFS-08 B737 Annual PPC Refresher',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-sfi-high-fdtl',
    instructor_name: 'Capt. Rajesh Gupta',
    instructor_role: 'SFI',
    resource_id: 'sim-b737-01',
    resource_name: 'B737 FFS-01',
    student_ids: ['stu-03', 'stu-04'],
    student_names: ['Tanya Sen', 'Siddharth Nair'],
    date: '2026-12-14',
    start_time: '14:00',
    end_time: '20:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
];

export const ATO_HISTORICAL_DUTY_LOGS: FDTLDutyRecord[] = [
  // Capt Rahul Sharma: Logged 2.0h earlier today, 14.0h earlier this week
  {
    id: 'fdtl-log-01',
    instructor_id: 'ins-sfi-a320',
    date: '2026-08-23',
    start_time: '08:00',
    end_time: '12:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    is_actual: true,
  },
  {
    id: 'fdtl-log-02',
    instructor_id: 'ins-sfi-a320',
    date: '2026-08-21',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    is_actual: true,
  },
  {
    id: 'fdtl-log-03',
    instructor_id: 'ins-sfi-a320',
    date: '2026-08-19',
    start_time: '14:00',
    end_time: '20:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    is_actual: true,
  },

  // Capt Rajesh Gupta: 5.5h in last 24h; 28.0h in rolling 7 days
  {
    id: 'fdtl-log-04',
    instructor_id: 'ins-sfi-high-fdtl',
    date: '2026-08-24',
    start_time: '02:00',
    end_time: '07:30',
    briefing_hours: 1.5,
    sim_hours: 4.0,
    total_duty_hours: 5.5,
    is_actual: true,
  },
  {
    id: 'fdtl-log-05',
    instructor_id: 'ins-sfi-high-fdtl',
    date: '2026-08-22',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    is_actual: true,
  },
  {
    id: 'fdtl-log-06',
    instructor_id: 'ins-sfi-high-fdtl',
    date: '2026-08-20',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    is_actual: true,
  },
  {
    id: 'fdtl-log-07',
    instructor_id: 'ins-sfi-high-fdtl',
    date: '2026-08-19',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    is_actual: true,
  },
];

export const ATO_STAGE_EVALUATIONS: StageEvaluationRecord[] = [
  {
    id: 'eval-01',
    student_id: 'stu-01',
    student_name: 'Aditi Rao',
    course_id: 'crs-a320-initial',
    stage_id: 'stg-a320-1',
    stage_name: 'Phase 1: A320 Technical Systems & Performance Written Exam',
    evaluation_date: '2026-07-20',
    evaluator_instructor_id: 'ins-tech-gi',
    evaluator_instructor_name: 'Capt. Hemant Kulkarni',
    score_percent: 94,
    outcome: 'PASSED',
    remedial_hours_required: 0,
    remarks: 'Excellent command of A320 electrical and fly-by-wire flight control laws. Scored 94/100.',
    cleared_for_next_stage: true,
  },
  {
    id: 'eval-02',
    student_id: 'stu-01',
    student_name: 'Aditi Rao',
    course_id: 'crs-a320-initial',
    stage_id: 'stg-a320-2',
    stage_name: 'Phase 1C: Multi-Crew Cooperation & Jet Induction Check',
    evaluation_date: '2026-08-05',
    evaluator_instructor_id: 'ins-sfi-a320',
    evaluator_instructor_name: 'Capt. Rahul Sharma',
    score_percent: 88,
    outcome: 'PASSED',
    remedial_hours_required: 0,
    remarks: 'Standard airline callouts, excellent CRM, proactive monitoring as Pilot Monitoring (PM).',
    cleared_for_next_stage: true,
  },
  {
    id: 'eval-03',
    student_id: 'stu-02',
    student_name: 'Rohan Verma',
    course_id: 'crs-a320-initial',
    stage_id: 'stg-a320-1',
    stage_name: 'Phase 1: A320 Technical Systems & Performance Written Exam',
    evaluation_date: '2026-07-20',
    evaluator_instructor_id: 'ins-tech-gi',
    evaluator_instructor_name: 'Capt. Hemant Kulkarni',
    score_percent: 91,
    outcome: 'PASSED',
    remedial_hours_required: 0,
    remarks: 'Sound understanding of fuel system and CFM56/LEAP powerplants. Passed above 80% cutoff.',
    cleared_for_next_stage: true,
  },
  {
    id: 'eval-04',
    student_id: 'stu-03',
    student_name: 'Tanya Sen',
    course_id: 'crs-b737-initial',
    stage_id: 'stg-b737-1',
    stage_name: 'Phase 1: B737 Technical Systems Progress Quiz',
    evaluation_date: '2026-08-20',
    evaluator_instructor_id: 'ins-tech-gi',
    evaluator_instructor_name: 'Capt. Hemant Kulkarni',
    score_percent: 68,
    outcome: 'FAILED',
    remedial_hours_required: 4.0,
    remarks: 'Below 80% minimum passing mark in Hydraulic System A/B and Standby Rudder logic. Remedial class required.',
    cleared_for_next_stage: false,
  },
  {
    id: 'eval-05',
    student_id: 'stu-05',
    student_name: 'Manish Pandey',
    course_id: 'crs-a320-transition',
    stage_id: 'stg-a320t-3',
    stage_name: 'Phase 2B: Simulator Progress Check',
    evaluation_date: '2026-08-22',
    evaluator_instructor_id: 'ins-sfi-turbo',
    evaluator_instructor_name: 'Capt. Vikram Mehra',
    score_percent: 74,
    outcome: 'REMEDIAL_REQUIRED',
    remedial_hours_required: 2.0,
    remarks: 'Rudder trim application delayed during single-engine missed approach. 2.0h remedial simulator practice assigned before Stage 4 skill check.',
    cleared_for_next_stage: false,
  },
];

export const ATO_ATTENDANCES: CadetAttendanceRecord[] = [
  {
    id: 'att-01',
    student_id: 'stu-01',
    session_code: 'FFS-04',
    session_title: 'FFS-04 Single Engine Profile',
    date: '2026-08-25',
    status: 'PRESENT',
  },
  {
    id: 'att-02',
    student_id: 'stu-02',
    session_code: 'FFS-04',
    session_title: 'FFS-04 Single Engine Profile',
    date: '2026-08-25',
    status: 'PRESENT',
  },
  {
    id: 'att-03',
    student_id: 'stu-03',
    session_code: 'GND-TECH-01',
    session_title: 'GND-TECH-01 Systems & Airframe',
    date: '2026-08-25',
    status: 'ABSENT',
    notes: 'Medical leave. Missed 4.0h Systems Airframe module. Requires makeup session to unlock simulator phase.',
  },
  {
    id: 'att-04',
    student_id: 'stu-04',
    session_code: 'GND-TECH-01',
    session_title: 'GND-TECH-01 Systems & Airframe',
    date: '2026-08-25',
    status: 'PRESENT',
  },
];
