import {
  Organisation,
  AircraftFleet,
  TrainingBatch,
  CadetStudent,
  InstructorProfile,
  SimulatorResource,
  CourseSyllabusItem,
  TrainingScheduleSession,
  FDTLDutyRecord,
} from '@/types';

export const ATO_ORGANISATION: Organisation = {
  id: 'org-gata-01',
  legal_name: 'Global Aviation Training Academy (GATA) Ltd.',
  trading_name: 'GATA Airline Training Center',
  ato_approval_number: 'DGCA/ATO/IND/2026/042',
  is_active: true,
};

export const ATO_FLEETS: AircraftFleet[] = [
  {
    id: 'fleet-a320',
    manufacturer: 'Airbus',
    model_name: 'A320',
    variant: 'CEO & NEO',
    type_rating_code: 'A320',
    category: 'JET',
    description: 'Airbus A320 family (CFM56, IAE V2500, LEAP-1A, PW1100G)',
  },
  {
    id: 'fleet-b737',
    manufacturer: 'Boeing',
    model_name: 'B737',
    variant: 'NG & MAX',
    type_rating_code: 'B737',
    category: 'JET',
    description: 'Boeing 737 Next Generation (-800/-900) & MAX 8/9 (LEAP-1B)',
  },
  {
    id: 'fleet-atr72',
    manufacturer: 'ATR',
    model_name: 'ATR 72',
    variant: '-600',
    type_rating_code: 'ATR-72-600',
    category: 'TURBOPROP',
    description: 'ATR 72-600 Glass Cockpit Regional Turboprop (PW127M)',
  },
  {
    id: 'fleet-q400',
    manufacturer: 'De Havilland',
    model_name: 'DHC-8 Q400',
    variant: 'Dash 8',
    type_rating_code: 'DHC-8-400',
    category: 'TURBOPROP',
    description: 'High-Speed Regional Turboprop (PW150A)',
  },
];

export const ATO_BATCHES: TrainingBatch[] = [
  {
    id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    batch_name: 'IndiGo Cadet A320 Type Rating Batch 26A',
    airline_operator: 'IndiGo Airlines',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    start_date: '2026-07-01',
    expected_completion_date: '2026-09-30',
    current_phase: 'SIM_FFS',
    progress_percentage: 65,
    students_count: 4,
    status: 'SIM_IN_PROGRESS',
  },
  {
    id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    batch_name: 'Air India Express B737 NG/MAX Batch 26B',
    airline_operator: 'Air India Express',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    start_date: '2026-08-10',
    expected_completion_date: '2026-11-15',
    current_phase: 'GROUND_TECH',
    progress_percentage: 20,
    students_count: 4,
    status: 'ACTIVE',
  },
  {
    id: 'batch-26c',
    batch_code: 'ALLIANCE-ATR-26C',
    batch_name: 'Alliance Air ATR 72-600 Transition Batch 26C',
    airline_operator: 'Alliance Air',
    aircraft_type_id: 'fleet-atr72',
    aircraft_type_name: 'ATR 72-600',
    start_date: '2026-07-15',
    expected_completion_date: '2026-10-15',
    current_phase: 'SIM_FFS',
    progress_percentage: 50,
    students_count: 2,
    status: 'SIM_IN_PROGRESS',
  },
  {
    id: 'batch-26d',
    batch_code: 'SPICE-Q400-26D',
    batch_name: 'SpiceJet DHC-8 Q400 Special TR Batch 26D',
    airline_operator: 'SpiceJet',
    aircraft_type_id: 'fleet-q400',
    aircraft_type_name: 'DHC-8 Q400',
    start_date: '2026-08-18',
    expected_completion_date: '2026-11-30',
    current_phase: 'GROUND_PERF',
    progress_percentage: 30,
    students_count: 2,
    status: 'ACTIVE',
  },
];

export const ATO_STUDENTS: CadetStudent[] = [
  {
    id: 'stu-01',
    student_number: 'CADET-26A-01',
    full_name: 'Aditi Rao',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    airline: 'IndiGo Airlines',
    ground_tech_completed: true,
    ground_perf_completed: true,
    sim_hours_completed: 16.0,
    skill_test_cleared: false,
    status: 'GROUND_CLEARED',
  },
  {
    id: 'stu-02',
    student_number: 'CADET-26A-02',
    full_name: 'Rohan Verma',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    airline: 'IndiGo Airlines',
    ground_tech_completed: true,
    ground_perf_completed: true,
    sim_hours_completed: 16.0,
    skill_test_cleared: false,
    status: 'GROUND_CLEARED',
  },
  {
    id: 'stu-03',
    student_number: 'CADET-26B-01',
    full_name: 'Tanya Sen',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    airline: 'Air India Express',
    ground_tech_completed: false,
    ground_perf_completed: false,
    sim_hours_completed: 0,
    skill_test_cleared: false,
    status: 'IN_TRAINING',
  },
  {
    id: 'stu-04',
    student_number: 'CADET-26B-02',
    full_name: 'Siddharth Nair',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    airline: 'Air India Express',
    ground_tech_completed: false,
    ground_perf_completed: false,
    sim_hours_completed: 0,
    skill_test_cleared: false,
    status: 'IN_TRAINING',
  },
  {
    id: 'stu-05',
    student_number: 'CADET-26C-01',
    full_name: 'Manish Pandey',
    batch_id: 'batch-26c',
    batch_code: 'ALLIANCE-ATR-26C',
    airline: 'Alliance Air',
    ground_tech_completed: true,
    ground_perf_completed: true,
    sim_hours_completed: 12.0,
    skill_test_cleared: false,
    status: 'GROUND_CLEARED',
  },
  {
    id: 'stu-06',
    student_number: 'CADET-26D-01',
    full_name: 'Pooja Hegde',
    batch_id: 'batch-26d',
    batch_code: 'SPICE-Q400-26D',
    airline: 'SpiceJet',
    ground_tech_completed: true,
    ground_perf_completed: false,
    sim_hours_completed: 0,
    skill_test_cleared: false,
    status: 'IN_TRAINING',
  },
];

export const ATO_INSTRUCTORS: InstructorProfile[] = [
  // 1. Technical Ground Instructor (Tech GI)
  {
    id: 'ins-tech-gi',
    staff_id: 'GI-TECH-101',
    full_name: 'Capt. Hemant Kulkarni',
    email: 'hemant.kulkarni@gata.aero',
    phone: '+91 98111 11001',
    roles: ['GI_TECH'],
    assigned_fleets: ['A320', 'B737', 'ATR 72-600', 'Q400'],
    dgca_approval_number: 'DGCA/GI/TECH/4081',
    dgca_approval_type: 'GI CAR (Technical)',
    base_month: 'June 2026',
    recurrent_expiry: '2027-06-30',
    recurrent_window_start: '2027-04-01',
    recurrent_status: 'VALID',
    is_locked_out: false,
    avatar_initials: 'HK',
  },

  // 2. Performance Ground Instructor / SME (Perf GI / SME)
  {
    id: 'ins-perf-gi',
    staff_id: 'GI-PERF-102',
    full_name: 'Capt. Sanjay Deshmukh',
    email: 'sanjay.deshmukh@gata.aero',
    phone: '+91 98111 11002',
    roles: ['GI_PERF'],
    assigned_fleets: ['A320', 'B737', 'ATR 72-600', 'Q400'],
    dgca_approval_number: 'DGCA/GI/SME/3319',
    dgca_approval_type: 'SME CAR (Performance & W&B)',
    base_month: 'June 2026',
    recurrent_expiry: '2027-06-30',
    recurrent_window_start: '2027-04-01',
    recurrent_status: 'VALID',
    is_locked_out: false,
    avatar_initials: 'SD',
  },

  // 3. SFI - Airbus A320
  {
    id: 'ins-sfi-a320',
    staff_id: 'SFI-A320-201',
    full_name: 'Capt. Rahul Sharma',
    email: 'rahul.sharma@gata.aero',
    phone: '+91 98111 22334',
    roles: ['SFI'],
    assigned_fleets: ['A320'],
    dgca_approval_number: 'DGCA/SFI/A320/8812',
    dgca_approval_type: 'SFI CAR (Level D)',
    base_month: 'June 2026',
    recurrent_expiry: '2027-06-30',
    recurrent_window_start: '2027-04-01',
    recurrent_status: 'VALID',
    is_locked_out: false,
    avatar_initials: 'RS',
  },

  // 4. SFI - Boeing 737 NG/MAX
  {
    id: 'ins-sfi-b737',
    staff_id: 'SFI-B737-202',
    full_name: 'Capt. Sarah Jenkins',
    email: 'sarah.jenkins@gata.aero',
    phone: '+91 98222 33445',
    roles: ['SFI'],
    assigned_fleets: ['B737'],
    dgca_approval_number: 'DGCA/SFI/B737/9011',
    dgca_approval_type: 'SFI CAR (Level D)',
    base_month: 'June 2026',
    recurrent_expiry: '2027-06-30',
    recurrent_window_start: '2027-04-01',
    recurrent_status: 'VALID',
    is_locked_out: false,
    avatar_initials: 'SJ',
  },

  // 5. SFI - Turboprop (ATR 72-600 & Q400) - Inside 3-Month Recurrent Window!
  {
    id: 'ins-sfi-turbo',
    staff_id: 'SFI-TURBO-203',
    full_name: 'Capt. Vikram Mehra',
    email: 'vikram.mehra@gata.aero',
    phone: '+91 98333 44556',
    roles: ['SFI'],
    assigned_fleets: ['ATR 72-600', 'Q400'],
    dgca_approval_number: 'DGCA/SFI/TURBO/7311',
    dgca_approval_type: 'SFI CAR (Level D)',
    base_month: 'June 2026',
    recurrent_expiry: '2026-09-15', // Expiring in 22 days!
    recurrent_window_start: '2026-06-15',
    recurrent_status: 'EXPIRING',
    is_locked_out: false,
    lockout_reason: 'Inside 3-Month TRS Recurrent Renewal Window (Expires 15 Sep 2026)',
    avatar_initials: 'VM',
  },

  // 6. SFI - A320 with High FDTL (Near 24h & 7d limits)
  {
    id: 'ins-sfi-high-fdtl',
    staff_id: 'SFI-A320-204',
    full_name: 'Capt. Rajesh Gupta',
    email: 'rajesh.gupta@gata.aero',
    phone: '+91 98444 55667',
    roles: ['SFI'],
    assigned_fleets: ['A320'],
    dgca_approval_number: 'DGCA/SFI/A320/6654',
    dgca_approval_type: 'SFI CAR (Level D)',
    base_month: 'June 2026',
    recurrent_expiry: '2027-06-30',
    recurrent_window_start: '2027-04-01',
    recurrent_status: 'VALID',
    is_locked_out: false,
    lockout_reason: 'Approaching DGCA CAR duty limits (5.5h / 6.0h in 24h; 28.0h / 30.0h in 7d)',
    avatar_initials: 'RG',
  },

  // 7. SFE (Synthetic Flight Examiner - A320/B737)
  {
    id: 'ins-sfe-chief',
    staff_id: 'SFE-CHIEF-301',
    full_name: 'Capt. Arun Kapur',
    email: 'arun.kapur@gata.aero',
    phone: '+91 98555 11223',
    roles: ['SFE', 'SFI'],
    assigned_fleets: ['A320', 'B737'],
    dgca_approval_number: 'DGCA/SFE/ALL/1001',
    dgca_approval_type: 'SFE CAR (Designated Examiner)',
    base_month: 'June 2026',
    recurrent_expiry: '2027-06-30',
    recurrent_window_start: '2027-04-01',
    recurrent_status: 'VALID',
    is_locked_out: false,
    avatar_initials: 'AK',
  },

  // 8. SFE - Missed Recurrent -> Status: REFRESHER_REQUIRED Lockout
  {
    id: 'ins-sfe-locked',
    staff_id: 'SFE-A320-302',
    full_name: 'Capt. Elena Rostova',
    email: 'elena.rostova@gata.aero',
    phone: '+91 98666 77889',
    roles: ['SFE'],
    assigned_fleets: ['A320'],
    dgca_approval_number: 'DGCA/SFE/A320/3309',
    dgca_approval_type: 'SFE CAR (Examiner)',
    base_month: 'June 2025',
    recurrent_expiry: '2026-06-30', // Missed recurrent!
    recurrent_window_start: '2026-04-01',
    recurrent_status: 'REFRESHER_REQUIRED',
    is_locked_out: true,
    lockout_reason: 'REFRESHER REQUIRED: 1-Year TRS Recurrent Check missed. Auto-locked out by DGCA CAR mandate.',
    avatar_initials: 'ER',
  },
];

export const ATO_SIMULATORS: SimulatorResource[] = [
  {
    id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    resource_category: 'FFS',
    level: 'Level D (Full Motion)',
    supported_aircraft_ids: ['fleet-a320'],
    supported_aircraft_names: ['Airbus A320 CEO', 'Airbus A320 NEO'],
    status: 'AVAILABLE',
    bay_location: 'Sim Bay 1 (CAE 7000XR)',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/FSTD/A320/019',
    approval_expiry: '2027-12-31',
  },
  {
    id: 'sim-b737-01',
    resource_name: 'B737 FFS-01',
    resource_category: 'FFS',
    level: 'Level D (Full Motion)',
    supported_aircraft_ids: ['fleet-b737'],
    supported_aircraft_names: ['Boeing B737 NG', 'Boeing B737 MAX'],
    status: 'AVAILABLE',
    bay_location: 'Sim Bay 2 (L3Harris RealitySeven)',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/FSTD/B737/022',
    approval_expiry: '2027-03-15',
  },
  {
    id: 'sim-atr72-01',
    resource_name: 'ATR 72-600 FFS-01',
    resource_category: 'FFS',
    level: 'Level D (Full Motion)',
    supported_aircraft_ids: ['fleet-atr72'],
    supported_aircraft_names: ['ATR 72-600'],
    status: 'AVAILABLE',
    bay_location: 'Sim Bay 3 (Thales Reality)',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/FSTD/ATR/008',
    approval_expiry: '2027-08-30',
  },
  {
    id: 'sim-q400-01',
    resource_name: 'Q400 FFS-01',
    resource_category: 'FFS',
    level: 'Level D (Full Motion)',
    supported_aircraft_ids: ['fleet-q400'],
    supported_aircraft_names: ['DHC-8 Q400'],
    status: 'AVAILABLE',
    bay_location: 'Sim Bay 4 (FlightSafety Int.)',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/FSTD/Q400/012',
    approval_expiry: '2027-10-15',
  },
  {
    id: 'sim-a320-ftd',
    resource_name: 'A320 FTD-01',
    resource_category: 'FTD',
    level: 'Level 2 (Fixed Base)',
    supported_aircraft_ids: ['fleet-a320'],
    supported_aircraft_names: ['Airbus A320 CEO'],
    status: 'AVAILABLE',
    bay_location: 'FTD Procedural Lab 1',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/FTD/A320/004',
    approval_expiry: '2026-12-31',
  },
  {
    id: 'room-alpha',
    resource_name: 'Classroom Alpha (Systems & Tech)',
    resource_category: 'CLASSROOM',
    level: '24-Seat Interactive CBT Lab',
    supported_aircraft_ids: ['fleet-a320', 'fleet-b737', 'fleet-atr72', 'fleet-q400'],
    supported_aircraft_names: ['All Fleets'],
    status: 'AVAILABLE',
    bay_location: 'Academic Wing Level 2',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/CLASS/01',
    approval_expiry: '2028-12-31',
  },
  {
    id: 'room-beta',
    resource_name: 'Classroom Beta (Performance & Flight Planning)',
    resource_category: 'CLASSROOM',
    level: '18-Seat Flight Planning Hub',
    supported_aircraft_ids: ['fleet-a320', 'fleet-b737', 'fleet-atr72', 'fleet-q400'],
    supported_aircraft_names: ['All Fleets'],
    status: 'AVAILABLE',
    bay_location: 'Academic Wing Level 2',
    approval_authority: 'DGCA India',
    approval_number: 'DGCA/CLASS/02',
    approval_expiry: '2028-12-31',
  },
];

export const ATO_SYLLABUS: CourseSyllabusItem[] = [
  // Phase 1A: Technical Ground School (Conducted by Tech GI)
  {
    id: 'syl-gnd-tech-01',
    aircraft_type_id: 'fleet-a320',
    phase: 'GROUND_TECH',
    session_code: 'GND-TECH-01',
    session_title: 'Aircraft Systems, Airframe & Electrics/Hydraulics',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 0.0,
    total_duty_hours: 4.0,
    required_instructor_role: 'GI_TECH',
    required_resource_category: 'CLASSROOM',
    is_check: false,
    description: 'Comprehensive systems walkthrough conducted by Technical Ground Instructor (Tech GI)',
  },
  {
    id: 'syl-gnd-tech-02',
    aircraft_type_id: 'fleet-a320',
    phase: 'GROUND_TECH',
    session_code: 'GND-TECH-02',
    session_title: 'Avionics, Autoflight, FMS & Powerplant Systems',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 0.0,
    total_duty_hours: 4.0,
    required_instructor_role: 'GI_TECH',
    required_resource_category: 'CLASSROOM',
    is_check: false,
    description: 'FMS logic and autoflight modes technical lecture',
  },

  // Phase 1B: Performance & W&B Ground School (Conducted by Perf GI / SME)
  {
    id: 'syl-gnd-perf-01',
    aircraft_type_id: 'fleet-a320',
    phase: 'GROUND_PERF',
    session_code: 'GND-PERF-01',
    session_title: 'Takeoff & Landing Performance, Weight & Balance',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 0.0,
    total_duty_hours: 4.0,
    required_instructor_role: 'GI_PERF',
    required_resource_category: 'CLASSROOM',
    is_check: false,
    description: 'Speeds (V1/VR/V2), runway analysis, obstacle clearance, loadsheets conducted by Perf GI / SME',
  },
  {
    id: 'syl-gnd-perf-02',
    aircraft_type_id: 'fleet-a320',
    phase: 'GROUND_PERF',
    session_code: 'GND-PERF-02',
    session_title: 'Operational Flight Planning, Enroute Weather & ETOPS',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 0.0,
    total_duty_hours: 4.0,
    required_instructor_role: 'GI_PERF',
    required_resource_category: 'CLASSROOM',
    is_check: false,
    description: 'OFP generation, fuel planning, alternate minima and dispatch limits',
  },

  // Phase 2: Simulator Training (Conducted by SFI with 2h Briefing + 4h Sim)
  {
    id: 'syl-ftd-01',
    aircraft_type_id: 'fleet-a320',
    phase: 'SIM_FTD',
    session_code: 'FTD-01',
    session_title: 'Cockpit Standard Operating Procedures & FMS Setup',
    duration_instructional_hours: 2.0,
    duration_briefing_hours: 2.0,
    total_duty_hours: 4.0,
    required_instructor_role: 'SFI',
    required_resource_category: 'FTD',
    is_check: false,
    description: 'Fixed-base procedure trainer: Pre-flight briefing (2h) + FTD session (2h)',
  },
  {
    id: 'syl-ffs-01',
    aircraft_type_id: 'fleet-a320',
    phase: 'SIM_FFS',
    session_code: 'FFS-01',
    session_title: 'Normal Handling, Visual Circuits & Crosswind Landings',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 2.0,
    total_duty_hours: 6.0,
    required_instructor_role: 'SFI',
    required_resource_category: 'FFS',
    is_check: false,
    description: 'Level D FFS: Pre/Post-Flight Briefing (2.0h) + Sim Flight (4.0h) = 6.0h total duty',
  },
  {
    id: 'syl-ffs-04',
    aircraft_type_id: 'fleet-a320',
    phase: 'SIM_FFS',
    session_code: 'FFS-04',
    session_title: 'Engine Failure After V1, Single-Engine Approaches',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 2.0,
    total_duty_hours: 6.0,
    required_instructor_role: 'SFI',
    required_resource_category: 'FFS',
    is_check: false,
    description: 'Critical emergency profile: V1 cut, single-engine missed approach, non-precision approach',
  },
  {
    id: 'syl-ffs-08',
    aircraft_type_id: 'fleet-a320',
    phase: 'SIM_FFS',
    session_code: 'FFS-08',
    session_title: 'Line Oriented Flight Training (LOFT) & Complex ECAM',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 2.0,
    total_duty_hours: 6.0,
    required_instructor_role: 'SFI',
    required_resource_category: 'FFS',
    is_check: false,
    description: 'Full real-time scenario from Delhi (VIDP) to Mumbai (VABB) with enroute weather & dual failure',
  },

  // Phase 3: Check & Licensing (Conducted by SFE Examiner)
  {
    id: 'syl-ca40',
    aircraft_type_id: 'fleet-a320',
    phase: 'SKILL_TEST',
    session_code: 'CA-40',
    session_title: 'DGCA CA-40 Day/Night Skill Test & PPC Check',
    duration_instructional_hours: 4.0,
    duration_briefing_hours: 2.0,
    total_duty_hours: 6.0,
    required_instructor_role: 'SFE',
    required_resource_category: 'FFS',
    is_check: true,
    description: 'Final Type Rating License Endorsement Skill Test conducted by DGCA Designated Examiner (SFE)',
  },
];

export const ATO_ACTIVE_SCHEDULES: TrainingScheduleSession[] = [
  {
    id: 'sch-01',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'FFS-04',
    session_title: 'FFS-04 Single Engine Profile',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFI',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01', 'stu-02'],
    student_names: ['Aditi Rao (PF)', 'Rohan Verma (PM)'],
    date: '2026-08-25',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'IN_PROGRESS',
  },
  {
    id: 'sch-02',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'GND-TECH-01',
    session_title: 'GND-TECH-01 Systems & Airframe',
    phase: 'GROUND_TECH',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-tech-gi',
    instructor_name: 'Capt. Hemant Kulkarni',
    instructor_role: 'GI_TECH',
    resource_id: 'room-alpha',
    resource_name: 'Classroom Alpha',
    student_ids: ['stu-03', 'stu-04'],
    student_names: ['Tanya Sen', 'Siddharth Nair'],
    date: '2026-08-25',
    start_time: '09:00',
    end_time: '13:00',
    briefing_hours: 0.0,
    sim_hours: 0.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-03',
    batch_id: 'batch-26d',
    batch_code: 'SPICE-Q400-26D',
    session_code: 'GND-PERF-01',
    session_title: 'GND-PERF-01 Performance & W&B',
    phase: 'GROUND_PERF',
    aircraft_type_id: 'fleet-q400',
    aircraft_type_name: 'DHC-8 Q400',
    instructor_id: 'ins-perf-gi',
    instructor_name: 'Capt. Sanjay Deshmukh',
    instructor_role: 'GI_PERF',
    resource_id: 'room-beta',
    resource_name: 'Classroom Beta',
    student_ids: ['stu-06'],
    student_names: ['Pooja Hegde'],
    date: '2026-08-25',
    start_time: '10:00',
    end_time: '14:00',
    briefing_hours: 0.0,
    sim_hours: 0.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-04',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'SKILL-TEST',
    session_title: 'CA-40 Pilot Proficiency Check (PPC)',
    phase: 'SKILL_TEST',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFE',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01'],
    student_names: ['Aditi Rao'],
    date: '2026-08-25',
    start_time: '15:00',
    end_time: '19:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-05',
    batch_id: 'batch-26c',
    batch_code: 'IX-ATR-26C',
    session_code: 'FTD-01',
    session_title: 'FTD-01 Normal SOPs & FMS Setup',
    phase: 'SIM_FTD',
    aircraft_type_id: 'fleet-atr72',
    aircraft_type_name: 'ATR 72-600',
    instructor_id: 'ins-sfi-high-fdtl',
    instructor_name: 'Capt. Rajesh Gupta',
    instructor_role: 'SFI',
    resource_id: 'sim-ftd-01',
    resource_name: 'Multi-Type FTD-01',
    student_ids: ['stu-05'],
    student_names: ['Alok Mehta'],
    date: '2026-08-25',
    start_time: '14:00',
    end_time: '18:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-06',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'FFS-05',
    session_title: 'FFS-05 Adverse Weather & Windshear',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFI',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01', 'stu-02'],
    student_names: ['Aditi Rao (PF)', 'Rohan Verma (PM)'],
    date: '2026-08-26',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-07',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'FTD-01',
    session_title: 'FTD-01 Cockpit Flows & CDU Setup',
    phase: 'SIM_FTD',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-sfi-high-fdtl',
    instructor_name: 'Capt. Rajesh Gupta',
    instructor_role: 'SFI',
    resource_id: 'sim-b737-01',
    resource_name: 'B737 FFS-01',
    student_ids: ['stu-03', 'stu-04'],
    student_names: ['Tanya Sen', 'Siddharth Nair'],
    date: '2026-08-26',
    start_time: '14:00',
    end_time: '18:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-08',
    batch_id: 'batch-26c',
    batch_code: 'IX-ATR-26C',
    session_code: 'GND-TECH-01',
    session_title: 'GND-TECH-01 PW127M Engine & Electrics',
    phase: 'GROUND_TECH',
    aircraft_type_id: 'fleet-atr72',
    aircraft_type_name: 'ATR 72-600',
    instructor_id: 'ins-tech-gi',
    instructor_name: 'Capt. Hemant Kulkarni',
    instructor_role: 'GI_TECH',
    resource_id: 'room-alpha',
    resource_name: 'Classroom Alpha',
    student_ids: ['stu-05'],
    student_names: ['Alok Mehta'],
    date: '2026-08-27',
    start_time: '09:00',
    end_time: '13:00',
    briefing_hours: 0.0,
    sim_hours: 0.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-09',
    batch_id: 'batch-26d',
    batch_code: 'SPICE-Q400-26D',
    session_code: 'FTD-01',
    session_title: 'FTD-01 High-Speed Turboprop SOPs',
    phase: 'SIM_FTD',
    aircraft_type_id: 'fleet-q400',
    aircraft_type_name: 'DHC-8 Q400',
    instructor_id: 'ins-sfi-high-fdtl',
    instructor_name: 'Capt. Rajesh Gupta',
    instructor_role: 'SFI',
    resource_id: 'sim-ftd-01',
    resource_name: 'Multi-Type FTD-01',
    student_ids: ['stu-06'],
    student_names: ['Pooja Hegde'],
    date: '2026-08-27',
    start_time: '14:00',
    end_time: '18:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-10',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'FFS-06',
    session_title: 'FFS-06 Line Oriented Flight Training (LOFT)',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFI',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01', 'stu-02'],
    student_names: ['Aditi Rao (PF)', 'Rohan Verma (PM)'],
    date: '2026-08-28',
    start_time: '10:00',
    end_time: '16:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-11',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'SKILL-TEST',
    session_title: 'CA-40 Final Skill Test & PPC',
    phase: 'SKILL_TEST',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFE',
    resource_id: 'sim-b737-01',
    resource_name: 'B737 FFS-01',
    student_ids: ['stu-03'],
    student_names: ['Tanya Sen'],
    date: '2026-08-29',
    start_time: '08:00',
    end_time: '12:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-12',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'FFS-07',
    session_title: 'FFS-07 Precision ILS CAT IIIB & Autoland',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFI',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01', 'stu-02'],
    student_names: ['Aditi Rao (PF)', 'Rohan Verma (PM)'],
    date: '2026-09-02',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-13',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'FFS-04',
    session_title: 'FFS-04 Non-Precision Approaches & Go-Arounds',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-sfi-high-fdtl',
    instructor_name: 'Capt. Rajesh Gupta',
    instructor_role: 'SFI',
    resource_id: 'sim-b737-01',
    resource_name: 'B737 FFS-01',
    student_ids: ['stu-03', 'stu-04'],
    student_names: ['Tanya Sen', 'Siddharth Nair'],
    date: '2026-09-08',
    start_time: '14:00',
    end_time: '20:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-14',
    batch_id: 'batch-26c',
    batch_code: 'IX-ATR-26C',
    session_code: 'SKILL-TEST',
    session_title: 'CA-40 ATR 72-600 Skill Test',
    phase: 'SKILL_TEST',
    aircraft_type_id: 'fleet-atr72',
    aircraft_type_name: 'ATR 72-600',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFE',
    resource_id: 'sim-ftd-01',
    resource_name: 'Multi-Type FTD-01',
    student_ids: ['stu-05'],
    student_names: ['Alok Mehta'],
    date: '2026-09-15',
    start_time: '09:00',
    end_time: '13:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-15',
    batch_id: 'batch-26d',
    batch_code: 'SPICE-Q400-26D',
    session_code: 'SKILL-TEST',
    session_title: 'CA-40 Q400 Skill Endorsement',
    phase: 'SKILL_TEST',
    aircraft_type_id: 'fleet-q400',
    aircraft_type_name: 'DHC-8 Q400',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFE',
    resource_id: 'sim-ftd-01',
    resource_name: 'Multi-Type FTD-01',
    student_ids: ['stu-06'],
    student_names: ['Pooja Hegde'],
    date: '2026-10-12',
    start_time: '10:00',
    end_time: '14:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-16',
    batch_id: 'batch-26a',
    batch_code: 'IND-A320-26A',
    session_code: 'FFS-08',
    session_title: 'FFS-08 Annual Recurrent & PPC Refresher',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-a320',
    aircraft_type_name: 'Airbus A320',
    instructor_id: 'ins-sfi-a320',
    instructor_name: 'Capt. Rahul Sharma',
    instructor_role: 'SFI',
    resource_id: 'sim-a320-01',
    resource_name: 'A320 FFS-01',
    student_ids: ['stu-01', 'stu-02'],
    student_names: ['Aditi Rao', 'Rohan Verma'],
    date: '2026-11-20',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
  {
    id: 'sch-17',
    batch_id: 'batch-26b',
    batch_code: 'AIX-B737-26B',
    session_code: 'FFS-08',
    session_title: 'FFS-08 B737 Annual PPC Refresher',
    phase: 'SIM_FFS',
    aircraft_type_id: 'fleet-b737',
    aircraft_type_name: 'Boeing B737',
    instructor_id: 'ins-sfi-high-fdtl',
    instructor_name: 'Capt. Rajesh Gupta',
    instructor_role: 'SFI',
    resource_id: 'sim-b737-01',
    resource_name: 'B737 FFS-01',
    student_ids: ['stu-03', 'stu-04'],
    student_names: ['Tanya Sen', 'Siddharth Nair'],
    date: '2026-12-14',
    start_time: '14:00',
    end_time: '20:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    status: 'CONFIRMED',
  },
];

export const ATO_HISTORICAL_DUTY_LOGS: FDTLDutyRecord[] = [
  // Capt Rahul Sharma: Logged 2.0h earlier today, 14.0h earlier this week
  {
    id: 'fdtl-log-01',
    instructor_id: 'ins-sfi-a320',
    date: '2026-08-23',
    start_time: '08:00',
    end_time: '12:00',
    briefing_hours: 1.0,
    sim_hours: 3.0,
    total_duty_hours: 4.0,
    is_actual: true,
  },
  {
    id: 'fdtl-log-02',
    instructor_id: 'ins-sfi-a320',
    date: '2026-08-21',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    is_actual: true,
  },
  {
    id: 'fdtl-log-03',
    instructor_id: 'ins-sfi-a320',
    date: '2026-08-19',
    start_time: '14:00',
    end_time: '20:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    is_actual: true,
  },

  // Capt Rajesh Gupta: 5.5h in last 24h; 28.0h in rolling 7 days
  {
    id: 'fdtl-log-04',
    instructor_id: 'ins-sfi-high-fdtl',
    date: '2026-08-24',
    start_time: '02:00',
    end_time: '07:30',
    briefing_hours: 1.5,
    sim_hours: 4.0,
    total_duty_hours: 5.5,
    is_actual: true,
  },
  {
    id: 'fdtl-log-05',
    instructor_id: 'ins-sfi-high-fdtl',
    date: '2026-08-22',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    is_actual: true,
  },
  {
    id: 'fdtl-log-06',
    instructor_id: 'ins-sfi-high-fdtl',
    date: '2026-08-20',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    is_actual: true,
  },
  {
    id: 'fdtl-log-07',
    instructor_id: 'ins-sfi-high-fdtl',
    date: '2026-08-19',
    start_time: '08:00',
    end_time: '14:00',
    briefing_hours: 2.0,
    sim_hours: 4.0,
    total_duty_hours: 6.0,
    is_actual: true,
  },
];
